config/routes.rb
Rails.application.routes.draw do
  get 'user/activity'
  get 'user/computers'
  resources :dashboard do
    collection do
      get :services
      put :set_auth
    end
  end
  resources :computer
  devise_for :users

  authenticated :user do
    root 'dashboard#index', as: :authenticated_root
  end
  root to: 'main#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/auth_record.rb
# == Schema Information
#
# Table name: auth_records
#
#  id         :bigint           not null, primary key
#  api_client :string
#  api_key    :string
#  user_id    :bigint
#
# Indexes
#
#  index_auth_records_on_user_id  (user_id)
#

class AuthRecord < ApplicationRecord
  belongs_to :user, dependent: :destroy
end

app/models/computer.rb
# == Schema Information
#
# Table name: computers
#
#  id                :bigint           not null, primary key
#  active            :boolean
#  connecter_guid    :string
#  connector_version :string
#  external_ip       :string
#  group_guid        :string
#  hostname          :string
#  install_date      :datetime
#  internal_ips      :string           default([]), is an Array
#  last_seen         :datetime
#  operating_system  :string
#  slug              :string
#  created_at        :datetime         not null
#  updated_at        :datetime         not null
#
# Indexes
#
#  index_computers_on_slug  (slug) UNIQUE
#

class Computer < ApplicationRecord
  extend FriendlyId
  has_many :user_activities, dependent: :destroy
  has_many :users, through: :user_activities
  has_many :vulnarabilities, dependent: :destroy

  friendly_id :slug_candidates, use: :slugged

  def slug_candidates
    ["#{rand(36**10).to_s(36)}-#{hostname}" ]
  end
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :bigint           not null, primary key
#  confirmation_sent_at   :datetime
#  confirmation_token     :string
#  confirmed_at           :datetime
#  current_sign_in_at     :datetime
#  current_sign_in_ip     :inet
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  failed_attempts        :integer          default(0), not null
#  is_admin               :boolean          default(FALSE)
#  last_sign_in_at        :datetime
#  last_sign_in_ip        :inet
#  locked_at              :datetime
#  name                   :string           default("")
#  remember_created_at    :datetime
#  reset_password_sent_at :datetime
#  reset_password_token   :string
#  sign_in_count          :integer          default(0), not null
#  unconfirmed_email      :string
#  unlock_token           :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#
# Indexes
#
#  index_users_on_confirmation_token    (confirmation_token) UNIQUE
#  index_users_on_email                 (email) UNIQUE
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#  index_users_on_unlock_token          (unlock_token) UNIQUE
#

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :trackable, :confirmable, :lockable

  has_many :user_activities
  has_many :computers, through: :user_activities
  has_one :auth_record

  validates_format_of :email, with:  /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
end

app/models/user_activity.rb
# == Schema Information
#
# Table name: user_activities
#
#  id            :bigint           not null, primary key
#  detected_date :datetime
#  detection     :string
#  event_type    :string
#  file          :jsonb
#  severity      :string
#  user_name     :string
#  computer_id   :bigint           not null
#  user_id       :bigint           not null
#
# Indexes
#
#  index_user_activities_on_computer_id  (computer_id)
#  index_user_activities_on_user_id      (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (computer_id => computers.id)
#  fk_rails_...  (user_id => users.id)
#

class UserActivity < ApplicationRecord
  belongs_to :user
  belongs_to :computer

  # This will allow us to strore the JSON data to postgres
  serialize :file, Hash
end

app/models/vulnarability.rb
# == Schema Information
#
# Table name: vulnarabilities
#
#  id          :bigint           not null, primary key
#  application :string
#  cves        :jsonb
#  file        :jsonb
#  latest_date :datetime
#  version     :string
#  computer_id :bigint
#
# Indexes
#
#  index_vulnarabilities_on_computer_id  (computer_id)
#

class Vulnarability < ApplicationRecord
  belongs_to :computer

  # This will allow us to strore the JSON data to postgres
  serialize :file, Hash
  serialize :aves, Array
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end

  def after_sign_out_path_for(resource_or_scope)
    root_path
  end

  def after_sign_in_path_for(resource_or_scope)
    authenticated_root_path
  end
end

app/controllers/computer_controller.rb
class ComputerController < ApplicationController
  before_action :fetch_computer, only: :show

  def show
  end

  private

    def fetch_computer
      @computer ||= Computer.friendly.find params[:id]
    end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :get_auth_record, only: [:services, :set_auth]
  before_action :check_access, only: [:services]

  def index
    @computers = Computer.order(:created_at).paginate(page: params[:page], per_page: 30)
    respond_to do |format|
      format.html
      format.js
    end
  end

  def services
  end

  # The Admin user CISCO credentials will be updated here
  def set_auth
    respond_to do |format|
      if @auth_record.update(auth_params)
        format.html { flash[:success] = "Credentials successfully updated." }
      else
        format.html { flash[:warning] = "Some Error occured while updating!" }
      end
      render :services
    end
  end

  private

    def auth_params
      params.require(:auth_record).permit(:api_client, :api_key)
    end

    def get_auth_record
      @auth_record ||= current_user.auth_record || current_user.build_auth_record
    end

    # This method will verify if the user is admin if not will redirect to dashboard
    def check_access
      unless policy(:dashboard).show?
        flash[:warning] = "You are not authorized to access that page!"
        redirect_to dashboard_index_path
      end
    end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  skip_before_action :authenticate_user!

  def index
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def activity
    @activities = current_user.user_activities.limit(10)
  end

  def computers
    @computers = current_user.computers.limit(10)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/computer/_activity.html.erb
<div class="card">
  <div class="card-header">
    <%= activity.user_name %>
  </div>
  <div class="card-body">
    <blockquote class="blockquote mb-0">
      User Name : <%= activity.user_name %></br>
      Severity : <%= activity.severity %></br>
      Activity File details : </br>
         File Name : <%= activity.file["file_name"] %></br>
         File Path : <%= activity.file["file_path"] %></br>
         Disposition : <%= activity.file["disposition"] %></br>
         Identity : <%= activity.file.dig("identity", "sha256")%></br></br>
    </blockquote>
  </div>
</div>

app/views/computer/_computer.html.erb
<div class="card">
  <div class="card-header">
    <h3> <%= computer.hostname %></h3>
  </div>
  <div class="card-body">
    <blockquote class="blockquote mb-0">
        <p class="lead">Computer Id : <%= computer.connecter_guid %></p>
        Operating System : <%= computer.operating_system %> </br>
        Active : <%= computer.active ? 'Yes' : 'No' %> </br>
        Connector Version : <%= computer.connector_version %> </br>
        Internal IP's : <%= computer.internal_ips.join(',') %> </br>
        External IP : <%= computer.external_ip %> </br>
        Group GUID : <%= computer.group_guid %> </br>
        Install Date : <%= computer.install_date %> </br>
        Last Seen : <%= computer.last_seen %> </br>
    </blockquote>
  </div>
</div>

app/views/computer/_computer_extra_info.html.erb
<ul class="nav nav-pills mb-3" role="tablist">
  <li class="nav-item">
    <a class="nav-link active" id="vulnarabilities" data-toggle="tab" href="#home" role="tab" aria-controls="home" aria-selected="true">Vulanarabilities (<span class="badge"><%= @computer.vulnarabilities.count %></span>)</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" id="user-activities" data-toggle="tab" href="#profile" role="tab" aria-controls="profile" aria-selected="false">User Activities (<span class="badge"><%= @computer.user_activities.count %></span>)</a>
  </li>
</ul>
<div class="tab-content">
  <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="vulnarabilities">
    <hr class="my-4">
    <div class="card-columns">
      <%= render partial: 'vulnarability', collection: @computer.vulnarabilities, as: :vulnerability %>
    </div>
  </div>
  <div class="tab-pane fade" id="profile" role="tabpanel" aria-labelledby="user-activities">
    <% if @computer.user_activities.present? %>
     <div class="card-columns">
        <%= render partial: 'activity', collection: @computer.user_activities, as: :activity %>
      </div>
    <% end %>
  </div>
</div>

app/views/computer/_vulnarability.html.erb
<div class="card">
  <div class="card-header">
    <%= vulnerability.application %>
  </div>
  <div class="card-body">
    <blockquote class="blockquote mb-0">
      Vulnarable Application : <%= vulnerability.application %></br>
      Vulnarable App Version : <%= vulnerability.version %></br>
      Vulnarable File details : </br>
         File Name : <%= vulnerability.file["filename"] %></br>
         Identity : <%= vulnerability.file["identity"]["sha256"] %></br></br>

      <b>CVES</b> : </br></br>
      <% vulnerability.cves.each do |cev| %>
        ID : <%= cev["id"] %></br>
        CVSS : <%= cev["cvss"] %></br>
        LINK : <%= cev["link"] %></br></br>
      <% end %>
    </blockquote>
  </div>
</div>

app/views/computer/show.html.erb
<div class="jumbotron">
  <hr class="my-4">
  <%= render partial: 'computer', collection: [@computer], as: :computer %>
  <%= render partial: 'computer_extra_info' %>
</div>

app/views/dashboard/_computer_card.html.erb
<div class="card" style="width:350px">
  <div class="card-body">
    <h4 class="card-title"><%= computer.hostname %></h4>
    <p class="card-text">Computer Id : <%= computer.connecter_guid %></p>
    <p class="card-text"> Operating System : <%= computer.operating_system %></p>
    <div class="card-footer">
      <%= link_to "see more details", computer_path(computer.slug), class: "btn btn-primary" %></br>
      <small class="text-muted">Last updated <%= time_ago_in_words(computer.updated_at) %> ago </small>
    </div>
  </div>
</div>

app/views/dashboard/index.html.erb
<div class="card-columns">
  <%= render partial: 'computer_card', collection: @computers, as: :computer %>
  <%= will_paginate @computers, renderer: WillPaginateInfinite::InfinitePagination %>
</div>

app/views/dashboard/index.js.erb
<%= infinite_append ".card-columns", @computers %>

app/views/dashboard/services.html.erb
<div class="container">
  <div class="card bg-light">
    <article class="card-body mx-auto" style="max-width: 400px;">
      <h4 class="card-title mt-3 text-center">Update Cisco API credentials</h4>
      <%= form_for @auth_record, url: set_auth_dashboard_index_path , method: :put, html: {class: "nifty_form"} do |f| %>
        <div class="form-group input-group">
          <div class="input-group-prepend">
            <span class="input-group-text"> API Client </span>
          </div>
           <%= f.text_field :api_client, placeholder: "API CLIENT", class: 'form-control'%>
        </div>
        <div class="form-group input-group">
          <div class="input-group-prepend">
            <span class="input-group-text"> API Key </span>
          </div>
           <%= f.text_field :api_key, placeholder: "API KEY", class: 'form-control'%>
        </div>
        <div class="form-group">
          <%= f.submit "Update", class: 'btn btn-primary btn-block' %>
        </div>
      <% end %>
    </article>
  </div>
</div>

app/views/layouts/_flash_notice.html.erb
<div class="container padded-container">
  <% flash.each do |key, value| %>
    <div class="alert alert-<%= key %> alert-dismissible fade show" role="alert">
      <%= value %>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  <% end %>
</div>

app/views/layouts/_nav_bar.html.erb
<nav class="navbar fixed-top navbar-default navbar-expand-xl navbar-light">
  <div class="navbar-header d-flex col">
    <% if user_signed_in? %>
      <%= link_to authenticated_root_path, class: 'navbar-brand' do %>
        <i class="fa fa-cube"></i>CISCO <b>AMP</b>
      <% end %>
    <% else %>
      <%= link_to root_path, class: 'navbar-brand' do %>
        <i class="fa fa-cube"></i>CISCO <b>AMP</b>
      <% end %>
    <% end %>
    <button type="button" data-target="#navbarCollapse" data-toggle="collapse" class="navbar-toggle navbar-toggler ml-auto">
      <span class="navbar-toggler-icon"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
  </div>
  <!-- Collection of nav links, forms, and other content for toggling -->
  <div id="navbarCollapse" class="collapse navbar-collapse justify-content-start">
    <ul class="nav navbar-nav navbar-right ml-auto">
      <% if user_signed_in? %>
        <% if policy(:dashboard).show? %>
          <li class="nav-item">
            <%= link_to "Services", services_dashboard_index_path, class: "nav-link" %>
          </li>
        <% end %>
        <li class="nav-item">
          <%= link_to "My Activity", user_activity_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "My Computers", user_computers_path, class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <a href="#" data-toggle="dropdown" class="nav-link dropdown-toggle user-action"><img src="https://www.tutorialrepublic.com/examples/images/avatar/2.jpg" class="avatar" alt="Avatar"> <%= current_user.name %> <b class="caret"></b></a>
          <ul class="dropdown-menu">
            <% if policy(:dashboard).show? %>
            <li>
              <%= link_to services_dashboard_index_path, class: "dropdown-item" do %>
                <i class="fa fa-sliders"></i> Settings
              <% end %>
            </li>
            <% end %>
            <li>
              <%= link_to edit_user_registration_path, class: "dropdown-item" do %>
                <i class="fa fa-user-o"></i> Profile
              <% end %>
            </li>
            <li class="divider dropdown-divider"></li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete, class: "dropdown-item" do %>
                <i class="material-icons">&#xE8AC;</i> Logout
              <% end %>
            </li>
          </ul>
        </li>
      <% else %>
        <li><%= link_to 'Log In', new_user_session_path, class: "nav-link" %></li>
        <li><%= link_to 'Sign Up', new_user_registration_path, class: "nav-link" %></li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>CISCO AMP</title>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%#= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link href="https://fonts.googleapis.com/css?family=Merienda+One" rel="stylesheet">
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
  </head>
  <body>
    <%= render partial: 'layouts/nav_bar' %>
    <%= render partial: 'layouts/flash_notice' %>
    <div class="container main-body">
      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/main.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>CISCO AMP</title>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%#= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

   <!--  <link href="https://fonts.googleapis.com/css?family=Merienda+One" rel="stylesheet">
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"> -->
  </head>
  <body class="home-page">
    <%= render partial: 'layouts/nav_bar' %>
    <%= render partial: 'layouts/flash_notice' %>
    <div class="container main-body">
      <%= yield %>
    </div>
  </body>
</html>

app/views/user/activity.html.erb
<div class="card-columns">
  <%= render partial: 'computer/activity', collection: @activities, as: :activity %>
</div>

app/views/user/computers.html.erb
<div class="card-columns">
  <%= render partial: 'computer/computer', collection: @computers, as: :computer %>
</div>